language: node_js
node_js:
 - "stable"
 script:
  - npm run test
after_success:
  - npm run coverage
  - codeclimate-test-reporter < ./coverage/lcov.info
  - nyc report --reporter=text-lcov | coveralls
