language: node_js
node_js:
 - "stable"
 script:
  - npm test
after_success:
  - npm run coverage
  - codeclimate-test-reporter < ./coverage/lcov.info
  - nyc report --reporter=text-lcov | coveralls
addons:
  code_climate:
    repo_token:
      secure: "c7a2d595fe08ea6448a8229daf63ad248a8779f8dceb2e50d2d1687abb2518b6"
